name: CI
on:
  pull_request:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"

      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare dependencies
        run: |
          go mod download

      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          golangci-lint run --fix ./...

      - name: Test
        run: |
          go test ./...
